name: Docker

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Pobranie kodu
      uses: actions/checkout@v4

    - name: Logowanie do GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }} 

    - name: Budowanie i wysyłanie obrazu
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ghcr.io/adrwierzbinska/ml-ci-cd/ml-api:latest
